
--Tabela de Beneficicario
CREATE TABLE TbBeneficiario(
    CPF CHAR(11) NOT NULL PRIMARY KEY,
    NM_BENEFICIARIO VARCHAR(55) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL
);
CREATE INDEX TBBENEFI_NOME_INDEX ON TbBeneficiario (NM_BENEFICIARIO);

--Tabela de especialidades
CREATE TABLE TbEspecialidade(
    COD_ESPECIALIDADE SERIAL NOT NULL PRIMARY KEY,
    NM_ESPECIALIDADE VARCHAR(55) NOT NULL
);
CREATE INDEX TBESPECIALIDADE_NOMEINDEX ON TbEspecialidade (NM_ESPECIALIDADE);

--Tabela de consultas
CREATE TABLE TbConsulta(
    COD_CONSULTA SERIAL NOT NULL PRIMARY KEY,
    COD_ESPECIALIDADE INTEGER NOT NULL,
    CPF_BENEFICIARIO CHAR(11) NOT NULL,
    DATA_HORA_CONSULTA TIMESTAMP NOT NULL,
    FOREIGN KEY (COD_ESPECIALIDADE) REFERENCES TbEspecialidade(COD_ESPECIALIDADE),
    FOREIGN KEY (CPF_BENEFICIARIO) REFERENCES TbBeneficiario(CPF)
);
CREATE INDEX TBCONSULTA_INDEX1 ON TbConsulta (COD_ESPECIALIDADE,CPF_BENEFICIARIO);